eip1271-skip-creation-validation = true

[native-price-estimation]
estimators = [[{ type = "Driver", name = "baseline", url = "http://driver/baseline" }]]

[database]
write-url = "%DB_WRITE_URL"
read-url = "%DB_READ_URL"